//STUDENTS
export const STUDENTS_LOADING = 'STUDENTS_LOADING';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAILED = 'GET_STUDENTS_FAILED';
export const CREATE_STUDENTS_SUCCESS = 'CREATE_STUDENTS_SUCCESS';
export const UPDATE_STUDENTS_SUCCESS = 'UPDATE_STUDENTS_SUCCESS';
export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS';

//GROUPS
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAILED = 'GET_GROUPS_FAILED';
export const CREATE_GROUPS_SUCCESS = 'CREATE_GROUPS_SUCCESS';
export const UPDATE_GROUPS_SUCCESS = 'UPDATE_GROUPS_SUCCESS';
export const DELETE_GROUPS_SUCCESS = 'DELETE_GROUPS_SUCCESS';

//CITIES
export const CITIES_LOADING = 'CITIES_LOADING';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILED = 'GET_CITIES_FAILED';

//PROFESSORS
export const PROFESSORS_LOADING = 'PROFESSORS_LOADING';
export const GET_PROFESSORS_SUCCESS = 'GET_PROFESSORS_SUCCESS';
export const GET_PROFESSORS_FAILED = 'GET_PROFESSORS_FAILED';